package com.valhallagame.notificationservice.model;

public enum NotificationType {
    PARTY_CANCEL_INVITE,
    PARTY_ACCEPT_INVITE,
    PARTY_DECLINE_INVITE,
    PARTY_SENT_INVITE,
    PARTY_LEAVE,
    PARTY_KICK_FROM_PARTY,
    PARTY_PROMOTE_LEADER,
    PARTY_SELECT_CHARACTER,
    FRIENDCHANGE,
    REWARDCHANGE,
    CHATCHANGE,
    PERSONCHANGE,
    DUNGEONACTIVE,
    CHAT_MESSAGE_RECEIVED,
    PARTY_RECEIVED_INVITE,
    FRIEND_RECEIVED_INVITE,
    DUNGEON_QUEUED,
    DUNGEON_FINISHING,
    DUNGEON_FINISHED,
    QUEUE_PLACEMENT_FULFILLED,
    PARTY_PERSON_ONLINE,
    PARTY_PERSON_OFFLINE,
    FRIEND_ONLINE,
    FRIEND_OFFLINE,
    FEAT_ADDED,
    FEAT_REMOVED,
    WARDROBE_ITEM_ADDED,
    WARDROBE_ITEM_REMOVED,
    TRAIT_LOCKED,
    TRAIT_UNLOCKED,
    RECIPE_ADDED,
    RECIPE_REMOVED;

    public String getValue() {
        return this.name();
    }
}